  sudo: true
  language: python
  python:
    - "3.6"
  install:
    - pip install -r requirements.txt
  script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test --debug-sql
  deploy:
    provider: heroku
    api_key: 7b182a2c-0bed-443c-9395-2069d64217f7
    app: pscaserv